/**
 * WsWorkunitsServiceSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.hpccsystems.ws.client.soap.wsworkunits;

public interface WsWorkunitsServiceSoap extends java.rmi.Remote {
    public org.hpccsystems.ws.client.soap.wsworkunits.GVCAjaxGraphResponse GVCAjaxGraph(org.hpccsystems.ws.client.soap.wsworkunits.GVCAjaxGraph parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUAbortResponse WUAbort(org.hpccsystems.ws.client.soap.wsworkunits.WUAbort parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUActionResponse WUAction(org.hpccsystems.ws.client.soap.wsworkunits.WUAction parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUAddLocalFileToWorkunitResponse WUAddLocalFileToWorkunit(org.hpccsystems.ws.client.soap.wsworkunits.WUAddLocalFileToWorkunit parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUDebugResponse WUCDebug(org.hpccsystems.ws.client.soap.wsworkunits.WUCDebug parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobQueueLOGResponse WUClusterJobQueueLOG(org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobQueueLOG parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobQueueXLSResponse WUClusterJobQueueXLS(org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobQueueXLS parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobSummaryXLSResponse WUClusterJobSummaryXLS(org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobSummaryXLS parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobXLSResponse WUClusterJobXLS(org.hpccsystems.ws.client.soap.wsworkunits.WUClusterJobXLS parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUCompileECLResponse WUCompileECL(org.hpccsystems.ws.client.soap.wsworkunits.WUCompileECL parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUCopyLogicalFilesResponse WUCopyLogicalFiles(org.hpccsystems.ws.client.soap.wsworkunits.WUCopyLogicalFiles parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUCreateResponse WUCreate() throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUUpdateResponse WUCreateAndUpdate(org.hpccsystems.ws.client.soap.wsworkunits.WUCreateAndUpdate parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUCreateZAPInfoResponse WUCreateZAPInfo(org.hpccsystems.ws.client.soap.wsworkunits.WUCreateZAPInfo parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUDeleteResponse WUDelete(org.hpccsystems.ws.client.soap.wsworkunits.WUDelete parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUDeployWorkunitResponse WUDeployWorkunit(org.hpccsystems.ws.client.soap.wsworkunits.WUDeployWorkunit parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUExportResponse WUExport(org.hpccsystems.ws.client.soap.wsworkunits.WUExport parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WULogFileResponse WUFile(org.hpccsystems.ws.client.soap.wsworkunits.WUFile parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUGVCGraphInfoResponse WUGVCGraphInfo(org.hpccsystems.ws.client.soap.wsworkunits.WUGVCGraphInfo parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUGetDependancyTreesResponse WUGetDependancyTrees(org.hpccsystems.ws.client.soap.wsworkunits.WUGetDependancyTrees parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUGetGraphResponse WUGetGraph(org.hpccsystems.ws.client.soap.wsworkunits.WUGetGraph parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUGetZAPInfoResponse WUGetZAPInfo(org.hpccsystems.ws.client.soap.wsworkunits.WUGetZAPInfo parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUGraphInfoResponse WUGraphInfo(org.hpccsystems.ws.client.soap.wsworkunits.WUGraphInfo parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUGraphTimingResponse WUGraphTiming(org.hpccsystems.ws.client.soap.wsworkunits.WUGraphTiming parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUInfoResponse WUInfo(org.hpccsystems.ws.client.soap.wsworkunits.WUInfo parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUInfoResponse WUInfoDetails(org.hpccsystems.ws.client.soap.wsworkunits.WUInfoDetails parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUJobListResponse WUJobList(org.hpccsystems.ws.client.soap.wsworkunits.WUJobList parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUListLocalFileRequiredResponse WUListLocalFileRequired(org.hpccsystems.ws.client.soap.wsworkunits.WUListLocalFileRequired parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUListQueriesResponse WUListQueries(org.hpccsystems.ws.client.soap.wsworkunits.WUListQueries parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUMultiQuerySetDetailsResponse WUMultiQuerysetDetails(org.hpccsystems.ws.client.soap.wsworkunits.WUMultiQuerysetDetails parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUProcessGraphResponse WUProcessGraph(org.hpccsystems.ws.client.soap.wsworkunits.WUProcessGraph parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUProtectResponse WUProtect(org.hpccsystems.ws.client.soap.wsworkunits.WUProtect parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUPublishWorkunitResponse WUPublishWorkunit(org.hpccsystems.ws.client.soap.wsworkunits.WUPublishWorkunit parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUPushEventResponse WUPushEvent(org.hpccsystems.ws.client.soap.wsworkunits.WUPushEvent parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQueryResponse WUQuery(org.hpccsystems.ws.client.soap.wsworkunits.WUQuery parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQueryConfigResponse WUQueryConfig(org.hpccsystems.ws.client.soap.wsworkunits.WUQueryConfig parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQueryDetailsResponse WUQueryDetails(org.hpccsystems.ws.client.soap.wsworkunits.WUQueryDetails parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQueryGetGraphResponse WUQueryGetGraph(org.hpccsystems.ws.client.soap.wsworkunits.WUQueryGetGraph parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQuerySetAliasActionResponse WUQuerysetAliasAction(org.hpccsystems.ws.client.soap.wsworkunits.WUQuerysetAliasAction parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQuerySetCopyQueryResponse WUQuerysetCopyQuery(org.hpccsystems.ws.client.soap.wsworkunits.WUQuerysetCopyQuery parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQuerySetDetailsResponse WUQuerysetDetails(org.hpccsystems.ws.client.soap.wsworkunits.WUQuerysetDetails parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQuerySetQueryActionResponse WUQuerysetQueryAction(org.hpccsystems.ws.client.soap.wsworkunits.WUQuerysetQueryAction parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUQuerysetsResponse WUQuerysets(org.hpccsystems.ws.client.soap.wsworkunits.WUQuerysets parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUResubmitResponse WUResubmit(org.hpccsystems.ws.client.soap.wsworkunits.WUResubmit parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUResultResponse WUResult(org.hpccsystems.ws.client.soap.wsworkunits.WUResult parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUResultBinResponse WUResultBin(org.hpccsystems.ws.client.soap.wsworkunits.WUResultBin parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUResultSummaryResponse WUResultSummary(org.hpccsystems.ws.client.soap.wsworkunits.WUResultSummary parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUResultViewResponse WUResultView(org.hpccsystems.ws.client.soap.wsworkunits.WUResultView parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WURunResponse WURun(org.hpccsystems.ws.client.soap.wsworkunits.WURun parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUScheduleResponse WUSchedule(org.hpccsystems.ws.client.soap.wsworkunits.WUSchedule parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUShowScheduledResponse WUShowScheduled(org.hpccsystems.ws.client.soap.wsworkunits.WUShowScheduled parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUSubmitResponse WUSubmit(org.hpccsystems.ws.client.soap.wsworkunits.WUSubmit parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUSyntaxCheckResponse WUSyntaxCheckECL(org.hpccsystems.ws.client.soap.wsworkunits.WUSyntaxCheckECL parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUUpdateResponse WUUpdate(org.hpccsystems.ws.client.soap.wsworkunits.WUUpdate parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUWaitResponse WUWaitCompiled(org.hpccsystems.ws.client.soap.wsworkunits.WUWaitCompiled parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
    public org.hpccsystems.ws.client.soap.wsworkunits.WUWaitResponse WUWaitComplete(org.hpccsystems.ws.client.soap.wsworkunits.WUWaitComplete parameters) throws java.rmi.RemoteException, org.hpccsystems.ws.client.soap.wsworkunits.ArrayOfEspException;
}
