name: 'Build HPCC K8s Image'
description: 'Builds and registers an HPCC K8s image'
inputs:
  os:
    description: 'Operating System'
    required: false
    default: 'ubuntu-22.04'
  asset-name:
    description: 'Asset Name'
    required: false
    default: 'docker-ubuntu-22_04-containerized'
  platform-folder:
    description: 'Platform Folder'
    required: false
    default: './HPCC-Platform'

runs:
  using: "composite"
  steps:
    - name: Free additional disk space (remove Android SDK + Tools)
      run: |
        sudo rm -rf /usr/local/lib/android
      shell: bash

    - name: Download Package
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.asset-name }}
        path: ${{ inputs.asset-name }}

    - name: Download Support Files
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.asset-name }}-support-files
        path: ${{ inputs.asset-name }}-support-files

    - name: Wait for registry startup
      run: |
        kubectl wait pods --for=jsonpath='{.status.phase}'=Running -l app=registry -n container-registry --timeout=90s
      shell: bash

    # Note: We need to move the package file due to the Dockerfile expecting it in the platform folder
    - name: Find & Move Package
      run: |
        k8s_pkg_path=$(ls -t ./${{ inputs.asset-name }}/*.deb 2>/dev/null | head -1)
        k8s_pkg_file=$(basename "$k8s_pkg_path")
        mv ${k8s_pkg_path} ${{ inputs.platform-folder }}/${k8s_pkg_file}
        echo "k8s_pkg_file=$k8s_pkg_file" >> $GITHUB_ENV
        echo "$k8s_pkg_file"
      shell: bash

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          network=host

    - name: Calculate vars
      id: vars
      run: |
        community_base_ref=${{ github.event.base_ref || github.ref }}
        candidate_branch=$(echo $community_base_ref | cut -d'/' -f3)
        echo "candidate_branch=$candidate_branch" >> $GITHUB_OUTPUT
        echo "candidate_base_branch=$(echo $candidate_branch | awk -F'.' -v OFS='.' '{ $3="x"; print }')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Docker Image (community)
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: ${{ inputs.platform-folder }}/dockerfiles/platform-core-ubuntu-22.04/Dockerfile
        context: ${{ inputs.platform-folder }}/
        push: true
        tags: localhost:32000/hpccsystems/platform-core:latest
        build-args: |
          PKG_FILE=${{ env.k8s_pkg_file }}
        cache-from: |
          type=registry,ref=hpccsystems/platform-core-${{ inputs.os }}:${{ steps.vars.outputs.candidate_base_branch }}
