name: Javadoc Test

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string

permissions:
  contents: read

jobs:
  javadoc-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head_sha }}

    - name: Set up JFrog release repository
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        server-id: 'jfrog'
        server-username: JFROG_USER
        server-password: JFROG_TOKEN

    - name: Set up JFrog snapshot repository
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        server-id: 'jfrog-snapshot'
        server-username: JFROG_USER
        server-password: JFROG_TOKEN

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build Javadoc
      run: mvn -B -Dmaven.test.skip=true clean javadoc:javadoc
      env:
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        JFROG_URL: ${{ vars.JFROG_URL }}