name: Test WSDL Client Stub Generation

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "master"
      - "candidate-*"
    paths:
      - "**/*.wsdl"

jobs:
  test-wsclient-stub:
    name: "Test WSDL Client Stub Generation"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test WSDL Client Stub Generation
        run: |
          echo "Testing WSDL client stub generation..."
          echo "Available Maven profiles:"
          mvn help:all-profiles | grep -A5 -B5 "generate.*stub" || true

          # Try the generate-wsclient-stub profile if it exists
          echo "Attempting to run generate-wsclient-stub profile..."
          if mvn -B -P generate-wsclient-stub process-resources; then
            echo "✅ generate-wsclient-stub profile executed successfully!"
          else
            echo "⚠️  generate-wsclient-stub profile not found or failed, trying alternative approaches..."

            # Try some of the existing stub generation profiles as examples
            echo "Testing with generate-wsworkunits-stub profile as fallback..."
            mvn -B -P generate-wsworkunits-stub process-resources || echo "Fallback profile also failed"
          fi

      - name: Verify Stub Generation Results
        run: |
          echo "Checking for generated stub files..."
          find wsclient/src/main/java -name "*.java" -newer wsclient/pom.xml | head -10 || true

          # Check if compilation still works after any WSDL changes
          echo "Testing compilation of wsclient module..."
          mvn -B compile -pl wsclient -q

          if [ $? -eq 0 ]; then
            echo "✅ WSDL client stub generation and compilation completed successfully!"
            echo "The WSDL changes do not break the client stub generation process."
          else
            echo "❌ WSDL client stub generation or compilation failed!"
            echo "The changes to WSDL files may have broken the wsclient stub generation process."
            exit 1
          fi